### ISSUE TITLE
Adding support for polygon mumbai

### ISSUE THREAD

**Issue by pesicsasa** [reservoirprotocol/marketplace-v2#322]
Can you add reference values for wagmi/chains.polygonMumbai? 
Referring to reservoirBaseUrl, proxyApi, routePrefix, etc.

**Comment by pedromcunha** [comment]
Yes, we're planning on exporting ReservoirChains that will make plugging them into the SDK/UI kit easier. It's in this PR https://github.com/reservoirprotocol/reservoir-kit/pull/327
