### ISSUE TITLE
Broken Currency Icons

### ISSUE THREAD

**Issue by gkalu** [reservoirprotocol/marketplace-v2#481]
After deploying locally (or even on live prod), the currency icons (like ETH and MATIC) do not come up.

![image](https://github.com/reservoirprotocol/marketplace-v2/assets/9148818/d5e79cf2-fcfd-474e-885c-98b165d631c9)

**Comment by ZimM-LostPolygon** [comment]
I've had the same issue. 

You have to use a proxy for certain links and images. I've copy-pasted the one from v1:
https://github.com/reservoirprotocol/marketplace-v1/blob/main/pages/api/reservoir/%5B...slug%5D.ts

Adjusted the env vars and currency icons were back!

**Comment by pedromcunha** [comment]
Yeah you need to adjust your env variables or edit the CurrencyIcon code.
