### ISSUE TITLE
Blur buy function of https://explorer.reservoir.tools/ makes funds disappear?

### ISSUE THREAD

**Issue by miracle2k** [reservoirprotocol/marketplace-v2#494]
I tried to purchase a Blur listing on one of these: https://explorer.reservoir.tools/ethereum/collection/0x78048feb296975e6ae7347f94b1a6d8d91a6f286

You can see the funds going to https://etherscan.io/address/0xf70da97812cb96acdf810712aa562db8dfa3dbef, a surprisingly busy EOA; no NFT was given in exchange.

This happened to be a Gnosis Safe multi sig transaction, but it seems reproducable with a EOA MetaMask/Rabby Wallet. Pick any Blur listing and it seems to be funds transfer straight to that wallet.

**Comment by pedromcunha** [comment]
Hi, this completely slipped and I'm so sorry about that. Are you still able to reproduce the issue? It may have already been patched, I know we had some issues in the past related to Blur. I'll also forward this to the rest of our engineering team.

**Comment by pedromcunha** [comment]
Any update here?
